wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1673860505.220632
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.13.9
      8:
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: GTSRB
epochs:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.001
