# config_cpu.yaml
workerPoolSpecs:
   machineSpec:
      machineType: n1-highmem-2
   replicaCount: 1
   containerSpec:
      imageUri: gcr.io/mlops-finalproject/trainer
      env:
         - name: WANDB_API_KEY
           value: eecad361deb7502a7ed9a7c225c73d5fd2e93381