wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673884800.654194
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 1
      - 16
      - 23
      4: 3.10.8
      5: 0.13.7
      8:
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: GTSRB
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
