name: "Run isort on project"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.x
        cache: 'pip'
      # - name: Cache stuff
      # uses: uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort


    - name: run isort on project
      run: |
        isort mlops_finalproject/
    